import {Runtime} from './runtime.mjs?v=22';
const runtime=new Runtime();window.footballRuntime=runtime;const $=id=>document.getElementById(id);let draft=null,lastTeamSignature='';
function button(text,onclick){const b=document.createElement('button');b.textContent=text;b.onclick=onclick;return b;}
function field(label,value,type='text'){const wrap=document.createElement('label');wrap.append(document.createTextNode(label));const input=document.createElement('input');input.type=type;input.value=value;wrap.append(input);return {wrap,input};}
function teamOptions(select,value){for(const team of draft.teams){const opt=document.createElement('option');opt.value=team.id;opt.textContent=team.name;select.append(opt);}select.value=value;}
function editors(){
  $('teamEditor').replaceChildren(...draft.teams.map((team,index)=>{const row=document.createElement('div');row.className='editor-row';for(const [key,label,type] of [['name','Ad','text'],['shortName','Kısa ad','text'],['color','Renk','color'],['secondaryColor','İkinci renk','color']]){const f=field(label,team[key],type);f.input.oninput=()=>team[key]=f.input.value;row.append(f.wrap);}const models=document.createElement('select');for(const [value,label]of [['./assets/models/player-a.glb?v=6','Oyuncu A · Sarı-lacivert'],['./assets/models/player-b-existing.glb?v=2','Oyuncu B · Sarı-kırmızı'],['','Basit yedek model']]){const opt=document.createElement('option');opt.value=value;opt.textContent=label;models.append(opt);}models.value=team.model;models.onchange=()=>team.model=models.value;row.append(models,button('Kaldır',()=>{draft.teams.splice(index,1);draft.giftMappings=draft.giftMappings.filter(g=>g.teamId!==team.id);editors();}));return row;}));
  $('giftEditor').replaceChildren(...draft.giftMappings.map((gift,index)=>{const row=document.createElement('div');row.className='editor-row';for(const [key,label,type]of [['giftId','Hediye kimliği','text'],['name','Ad','text'],['shots','Şut','number'],['points','Gol puanı','number']]){const f=field(label,gift[key],type);f.input.oninput=()=>gift[key]=type==='number'?Number(f.input.value):f.input.value;row.append(f.wrap);}const select=document.createElement('select');teamOptions(select,gift.teamId);select.onchange=()=>gift.teamId=select.value;row.append(select,button('Kaldır',()=>{draft.giftMappings.splice(index,1);editors();}));return row;}));$('probability').value=Math.round(draft.gameSettings.goalProbability*100);
}
function render(state){
  $('connectionStatus').textContent=`${state.connection.mode==='mock'?'Demo':'TikTok'} · ${({connected:'Bağlı',connecting:'Bağlanıyor',disconnected:'Bağlantı kapalı',error:'Bağlantı hatası'})[state.connectionStatus]||state.connectionStatus}`;
  const active=state.animationState;$('activeStatus').textContent=active?`${state.teams.find(t=>t.id===active.teamId)?.name} · ${active.phase} · Sırada ${state.eventQueue.length} şut`:`Oyuncular hazır · Sırada ${state.eventQueue.length} şut`;
  const signature=JSON.stringify(state.teams);
  if(signature!==lastTeamSignature){lastTeamSignature=signature;draft=JSON.parse(JSON.stringify(state));editors();$('mode').value=state.connection.mode;$('bridgeUrl').value=state.connection.bridgeUrl;}
  $('shotTests').replaceChildren(...state.teams.map(t=>button(t.name+' şut',()=>runtime.command('shot',{teamId:t.id,result:$('outcome').value}))));
  $('giftTests').replaceChildren(...state.giftMappings.map(g=>button(g.name+' → '+(state.teams.find(t=>t.id===g.teamId)?.shortName||g.teamId),()=>runtime.command('gift',{giftId:g.giftId,count:Number($('giftCount').value)}))));
  // Preserve an actively edited score input while queue snapshots arrive.
  if(!$('scoreControls').contains(document.activeElement))$('scoreControls').replaceChildren(...state.teams.map(t=>{const row=document.createElement('div');row.className='score-row';const name=document.createElement('span');name.textContent=t.name;const f=field('',state.scores[t.id],'number');f.input.min=0;row.append(name,f.wrap,button('Kaydet',()=>runtime.command('score',{teamId:t.id,value:f.input.value})));return row;}));
  if(document.activeElement!==$('volume'))$('volume').value=state.audioSettings.volume;$('audioEnabled').checked=state.audioSettings.enabled;$('crowd').checked=state.audioSettings.crowd;
  $('eventLog').replaceChildren(...state.eventLog.slice(0,30).map(item=>{const li=document.createElement('li');li.textContent=new Date(item.at).toLocaleTimeString('tr-TR')+' · '+item.message;return li;}));
}
$('connect').onclick=()=>runtime.command('connection',{mode:$('mode').value,bridgeUrl:$('bridgeUrl').value});$('disconnect').onclick=()=>runtime.command('disconnect');$('clearQueue').onclick=()=>runtime.command('clearQueue');$('reset').onclick=()=>runtime.command('reset');
for(const id of ['audioEnabled','crowd','volume'])$(id).onchange=()=>runtime.command('audio',{enabled:$('audioEnabled').checked,crowd:$('crowd').checked,volume:Number($('volume').value)});
$('goalSound').onclick=()=>runtime.command('audioTest',{sound:'goal'});$('saveSound').onclick=()=>runtime.command('audioTest',{sound:'save'});
for(const b of document.querySelectorAll('[data-social]'))b.onclick=()=>runtime.command('social',{type:b.dataset.social});
$('addTeam').onclick=()=>{if(draft.teams.length>=6){$('notice').textContent='En fazla 6 takım eklenebilir.';return;}draft.teams.push({id:'team-'+crypto.randomUUID().slice(0,8),name:'Yeni takım',shortName:'YT',color:'#7bcced',secondaryColor:'#174d5c',model:'./assets/models/player-a.glb?v=6'});editors();};
$('addGift').onclick=()=>{if(!draft.teams.length)return;draft.giftMappings.push({giftId:'gift-'+draft.giftMappings.length,name:'Yeni hediye',teamId:draft.teams[0].id,shots:1,points:1});editors();};
$('saveConfig').onclick=()=>{draft.gameSettings.goalProbability=Number($('probability').value)/100;draft.audioSettings={...runtime.state.audioSettings};draft.connection={...runtime.state.connection};runtime.command('config',draft);};
runtime.addEventListener('state',({detail})=>render(detail));runtime.addEventListener('error',({detail})=>$('notice').textContent=detail);render(runtime.state);
