export class StadiumAudio {
  constructor(){this.ctx=null;this.master=null;this.ambience=null;this.settings={enabled:false,crowd:true,volume:.45};this.last=new Map();}
  async unlock(){if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.connect(this.ctx.destination);}await this.ctx.resume();this.apply(this.settings);}
  apply(settings){this.settings=settings;if(!this.ctx)return;this.master.gain.setTargetAtTime(settings.enabled?settings.volume:0,this.ctx.currentTime,.12);if(settings.enabled&&settings.crowd&&!this.ambience)this.startCrowd();if((!settings.enabled||!settings.crowd)&&this.ambience){this.ambience.stop();this.ambience.disconnect();this.ambience=null;}}
  noise(seconds){const buffer=this.ctx.createBuffer(1,Math.ceil(this.ctx.sampleRate*seconds),this.ctx.sampleRate),data=buffer.getChannelData(0);let previous=0;for(let i=0;i<data.length;i++){previous=(previous+(Math.random()*2-1)*.12)/1.08;data[i]=previous*2;}return buffer;}
  startCrowd(){const source=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter(),gain=this.ctx.createGain();source.buffer=this.noise(8);source.loop=true;filter.type='lowpass';filter.frequency.value=1100;gain.gain.value=.13;source.connect(filter).connect(gain).connect(this.master);source.start();this.ambience=source;}
  play(kind){if(!this.ctx||this.ctx.state!=='running'||!this.settings.enabled)return;const now=this.ctx.currentTime;if(now-(this.last.get(kind)??-100)<.18)return;this.last.set(kind,now);if(kind==='goal'){this.burst(1.8,.65,1800);[392,494,587,784].forEach((f,i)=>this.tone(f,now+i*.1,.4,.09));}else if(kind==='kick')this.tone(100,now,.14,.3,true);else this.burst(kind==='net'?.25:.35,.22,kind==='net'?1800:600);}
  tone(freq,at,duration,volume,drop=false){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.setValueAtTime(freq,at);if(drop)o.frequency.exponentialRampToValueAtTime(35,at+duration);g.gain.setValueAtTime(.001,at);g.gain.exponentialRampToValueAtTime(volume,at+.015);g.gain.exponentialRampToValueAtTime(.001,at+duration);o.connect(g).connect(this.master);o.start(at);o.stop(at+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
  burst(duration,volume,frequency){const source=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter(),gain=this.ctx.createGain(),at=this.ctx.currentTime;source.buffer=this.noise(duration);filter.type='lowpass';filter.frequency.value=frequency;gain.gain.setValueAtTime(.001,at);gain.gain.exponentialRampToValueAtTime(volume,at+.03);gain.gain.exponentialRampToValueAtTime(.001,at+duration);source.connect(filter).connect(gain).connect(this.master);source.start();source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}
}
