import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,validateConfig,DEFAULT_CONFIG} from '../config.mjs';
import {FootballEngine,RESULT_MS,shotDuration} from '../engine.mjs';
import {MockLiveEventAdapter,TikTokLiveEventAdapter} from '../adapters.mjs';
function harness(){let clock=0,serial=0;const state=initialState();const engine=new FootballEngine(state,{now:()=>clock,id:()=>String(++serial),random:()=>.1,persist:()=>{}});return {state,engine,advance:ms=>{clock+=ms;engine.tick();}};}
test('burst gifts stay bounded and only one shot is active',()=>{const {state,engine}=harness();for(let i=0;i<40;i++)engine.gift({id:'gift-'+i,giftId:'rose',repeatCount:20,repeatEnd:true});assert(state.animationState);assert.equal(state.eventQueue.length,200);assert.equal(state.scores.A,0);});
test('streak updates are ignored and final event is deduplicated',()=>{const {state,engine}=harness();engine.gift({id:'one',giftId:'rose',repeatCount:3,repeatEnd:false});assert.equal(state.animationState,null);engine.gift({id:'one',giftId:'rose',repeatCount:3,repeatEnd:true});engine.gift({id:'one',giftId:'rose',repeatCount:3,repeatEnd:true});assert.equal(state.eventQueue.length,2);});
test('goal scores exactly once at impact; save never scores; next shot waits for return',()=>{const {state,engine,advance}=harness();engine.enqueue('A',{forcedResult:'goal',points:3});engine.enqueue('B',{forcedResult:'save'});const first=state.animationState.id;advance(RESULT_MS-1);assert.equal(state.scores.A,0);advance(1);assert.equal(state.scores.A,3);advance(100);assert.equal(state.scores.A,3);assert.equal(state.animationState.id,first);advance(shotDuration('goal')-RESULT_MS-100);assert.equal(state.animationState.teamId,'B');advance(RESULT_MS);assert.equal(state.scores.B,0);assert.equal(state.lastResult.result,'save');advance(shotDuration('save')-RESULT_MS);assert.equal(state.animationState,null);});
test('unknown gifts, malformed counts and unknown teams do not create jobs',()=>{const {state,engine}=harness();engine.gift({id:'x',giftId:'missing'});engine.gift({id:'y',giftId:'rose',repeatCount:'oops'});assert.equal(state.animationState,null);assert.throws(()=>engine.enqueue('unknown'));});
test('new team and gift mapping use config, with weighted goal points',()=>{const {state,engine,advance}=harness();const config=structuredClone(DEFAULT_CONFIG);config.teams.push({id:'D',name:'Mor',shortName:'M',color:'#a268dd',secondaryColor:'#ffffff',model:''});config.giftMappings.push({giftId:'star',name:'Star',teamId:'D',shots:2,points:2});engine.configure(config);engine.gift({id:'d',giftId:'star'});assert.equal(state.animationState.teamId,'D');assert.equal(state.eventQueue.length,1);advance(RESULT_MS);assert.equal(state.scores.D,2);});
test('reset cancels active shot and queue, avoiding a delayed score',()=>{const {state,engine,advance}=harness();engine.enqueue('A',{count:5,forcedResult:'goal'});engine.reset();advance(20000);assert.equal(state.animationState,null);assert.equal(state.eventQueue.length,0);assert.deepEqual(state.scores,{A:0,B:0,C:0});});
test('config rejects duplicate team/gift IDs, orphan mapping and unsafe model URLs',()=>{const config=structuredClone(DEFAULT_CONFIG);assert.equal(validateConfig(config).teams.length,3);config.teams.push(config.teams[0]);assert.throws(()=>validateConfig(config));config.teams.pop();config.giftMappings[0].teamId='unknown';assert.throws(()=>validateConfig(config));config.giftMappings[0].teamId='A';config.teams[0].model='javascript:alert(1)';assert.throws(()=>validateConfig(config));});
test('mock adapter connect/disconnect and all event hooks',async()=>{const mock=new MockLiveEventAdapter();const seen=[];mock.onGift(e=>seen.push(e.giftId));mock.onLike(()=>seen.push('like'));mock.onFollow(()=>seen.push('follow'));mock.onComment(e=>seen.push(e.text));await mock.connect();mock.gift('rose');mock.like();mock.follow();mock.comment('hello');assert.deepEqual(seen,['rose','like','follow','hello']);mock.disconnect();assert.throws(()=>mock.gift('rose'));});
test('TikTok bridge accepts protocol events and rejects insecure remote endpoints',async()=>{class Socket{constructor(){queueMicrotask(()=>this.onopen());}close(){this.onclose?.();}}const adapter=new TikTokLiveEventAdapter('wss://bridge.example',{WebSocketImpl:Socket});let gift;adapter.onGift(e=>gift=e);await adapter.connect();adapter.socket.onmessage({data:JSON.stringify({type:'gift',data:{id:'real1',giftId:'rose',repeatEnd:true}})});assert.equal(gift.id,'real1');adapter.socket.onmessage({data:'invalid'});adapter.disconnect();assert.equal(adapter.connected,false);await assert.rejects(new TikTokLiveEventAdapter('ws://unsafe.example',{WebSocketImpl:Socket}).connect());});
